### Task 1

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3, 3, 1]])

In [4]:
b = np.array([[6, 8, 11, 10, 7]])

In [5]:
a = np.hstack((a.T,b.T))
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Task 2

In [7]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Task 3

In [12]:
a_centered_sp = np.dot(a_centered[:, 1], a_centered[:, 0])
a_centered_sp / (a.shape[0] - 1)

2.0

### Task 4

In [13]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

In [14]:
np.cov(a.T)[0][1]

2.0

## Работа с данными в Pandas

### Task 1

In [3]:
import pandas as pd

In [13]:
authors = pd.DataFrame ({
    "author_id":  [1, 2, 3],
    "author_name": ['Тургенев', 'Чехов', 'Островский']
})


In [14]:
authors.set_index("author_id", inplace = True)

In [15]:
authors

author_name
author_id            
1            Тургенев
2               Чехов
3          Островский

In [77]:
book = pd.DataFrame ({
    "author_id": [1, 1, 1, 2, 2, 3, 3], 
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]
})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Task 2

In [32]:
authors_price = pd.merge(authors, book, on = "author_id", how = "inner")
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Task 3

In [48]:
top5 = authors_price.copy()
top5.sort_values(by="price", inplace = True, ascending=False)
top5.head(5)

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Task 4

In [75]:
authors_stat = authors_price.copy()
authors_stat.drop("author_id", axis = 1, inplace = True)
authors_stat.drop("book_title", axis = 1, inplace = True)

In [76]:
authors_stat = authors_price.groupby('author_name')['price'].agg(['min', 'max', 'mean'])
authors_stat

min  max        mean
author_name                      
Островский   290  370  330.000000
Тургенев     300  450  366.666667
Чехов        450  500  475.000000